See  https://hatmarch.github.io/container-workshop/[workshop documentation] for assets generated from this workshop

[NOTE]
====
This repo has *submodules*.  To clone this repo, use this command to also clone submodules:

----
git clone --recurse-submodules https://github.com/hatmarch/cdc-data-monolith
----

====

== Documentation Updates

Documentation is generated by antora.  To change and build the documentation locally, once running the project within Visual Studio Code Remote Development Containers, you can run the following command in the terminal

----
# NOTE: npm install command is only necessary the first time you run this
npm install 
gulp
----

This will run a javascript process that will build the documentation according to link:dev-site.yml[dev-site.yml], host it locally, and watch the relevant directories so that you can see changes in real time.

Documentation files can be found in the `${DEMO_HOME}/documentation` directory

== Publish documentation

When you are happy with the documentation changes, you can run the following command to deploy these changes externally (based on the contents of link:site.yml[site.yml])

----
${DEMO_HOME}/scripts/github-pages-publish.sh
----