See  https://hatmarch.github.io/container-workshop/[workshop documentation] for assets generated from this workshop

// [NOTE]
// ====
// This repo has *submodules*.  To clone this repo, use this command to also clone submodules:

// ----
// git clone --recurse-submodules https://github.com/hatmarch/cdc-data-monolith
// ----

// ====

== Documentation Updates

Documentation is generated by antora.  The easiest way to generate the documentation is to run this repo within Visual Studio with Remote Container extensions enabled.  See link:https://hatmarch.github.io/java-operator-sdk-tutorial/java-operator-tutorial/demo/setup.html[here] for more info

Once running the project within Visual Studio Code Remote Development Containers (or locally on a system with the proper npm libraries installed), you can run the following command in the terminal:

[NOTE]
====
npm install command is only necessary _the first time you run this_
====

----
npm install 
gulp
----

This will run a javascript process that will build the documentation according to link:dev-site.yml[dev-site.yml], host it locally, and watch the relevant directories so that you can see changes in real time.

Documentation files can be found in the `${DEMO_HOME}/documentation` directory

== Publish documentation

When you are happy with the documentation changes, you can run the following command to deploy these changes externally (based on the contents of link:site.yml[site.yml])

----
${DEMO_HOME}/scripts/github-pages-publish.sh
----