FROM quay.io/mhildenb/container-workshop-base:latest

USER root

RUN pip3 install --upgrade boto3 boto

# make python 3 the default python (that ansible uses)
RUN ln -s /usr/bin/python3 /usr/bin/python

# USER jboss
